# Generated by Django 3.2 on 2023-01-09 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20230108_1939'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='download_link',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
